# Generated by Django 4.2.2 on 2023-06-30 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnrollmentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnici',
            name='role',
            field=models.CharField(choices=[('administrator', 'ADMINISTRATOR'), ('profesor', 'PROFESOR'), ('student', 'STUDENT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='korisnici',
            name='status',
            field=models.CharField(choices=[('none', 'NONE'), ('redovan', 'REDOVAN'), ('izvanredan', 'IZVANREDAN')], max_length=20),
        ),
        migrations.AlterField(
            model_name='predmeti',
            name='izborni',
            field=models.CharField(choices=[('da', 'da'), ('ne', 'ne')], max_length=10),
        ),
        migrations.AlterField(
            model_name='predmeti',
            name='nositelj',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Enrolled', 'ENROLLED'), ('Passed', 'PASSED'), ('Failed', 'FAILED')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnrollmentApp.predmeti')),
            ],
        ),
    ]
